WebPrototype/WebPrototype/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('settings/', views.SettingsView.as_view(), name='settings'),
    path('flightdata/', include('flightdata.urls')),
    path('errors/', include('errors.urls')),
    path('admin/', admin.site.urls),
]

WebPrototype/errors/urls.py
from django.urls import path, include

from . import views, api_views

api_patterns = [
    path('scrapersettings', api_views.ScraperSettingAPIView.as_view(),
         name='api_scraper_settings'),
    # ex: /errors/scrapersessions
    path('scrapersessions', api_views.ScraperSessionAPIView.as_view(),
         name='api_scraper_sessions'),
    # ex: /errors/scraperlogs
    path('scraperlogs', api_views.ScraperLogAPIView.as_view(),
         name='api_scraper_logs'),
    # ex: /errors/scrapererrors
    path('scrapererrors', api_views.ScraperErrorAPIView.as_view(),
         name='api_scraper_errors'),
]

app_name = "errors"
urlpatterns = [
    # ex: /errors/scrapersettings
    path('scrapersettings', views.ScraperSettingView.as_view(),
         name='scraper_settings'),
    # ex: /errors/scrapersessions
    path('scrapersessions', views.ScraperSessionView.as_view(),
         name='scraper_sessions'),
    # ex: /errors/scraperlogs
    path('scraperlogs', views.ScraperLogView.as_view(), name='scraper_logs'),
    # ex: /errors/scrapererrors
    path('scrapererrors', views.ScraperErrorView.as_view(), name='scraper_errors'),
    path('api/', include((api_patterns, "json")), {"fmt":"json"}),
    path('csv/', include((api_patterns, "csv")), {"fmt":"csv"}),
]

WebPrototype/flightdata/urls.py
from django.urls import path, include

from . import views, api_views

api_patterns = [
    path('airports', api_views.AirportAPIView.as_view(), name='api_airports'),
    path('airlines', api_views.AirlineAPIView.as_view(), name='api_airlines'),
    path('aircraft', api_views.AircraftAPIView.as_view(), name="api_aircraft"),
    path('flights', api_views.FlightInfoAPIView.as_view(), name='api_flight_info'),
    path('flightstatus', api_views.FlightStatusAPIView.as_view(),
         name='api_flight_status'),
    path('airfares', api_views.AirfareAPIView.as_view(), name="api_airfares"),
    path('routes', api_views.TrackedRouteAPIView.as_view(), name="api_routes"),
]

app_name = "flightdata"
urlpatterns = [
    # ex: /flightdata/airports
    path('airports', views.AirportView.as_view(), name='airports'),
    # ex: /flightdata/airlines
    path('airlines', views.AirlineView.as_view(), name='airlines'),
    # ex: /flightdata/aircraft
    path('aircraft', views.AircraftView.as_view(), name='aircrafts'),
    # ex: /flightdata/flights
    path('flights', views.FlightInfoView.as_view(), name='flight_info'),
    # ex: /flightdata/flights/<flight_number>
    path('flights/<str:flight_number>',
         views.FlightStatusView.as_view(), name='flight_status'),
    # ex: /flightdata/airfares
    path('airfares', views.AirfareView.as_view(), name='airfares'),
    # ex: /flightdata/airfares/<flight_number>
    path('airfares/<str:flight_number>', views.AirfareFlightView.as_view(), name='airfare'),
    # ex: /flightdata/routes
    path('routes', views.TrackedRouteView.as_view(), name='routes'),
    path('api/', include((api_patterns, "json")), {"fmt":"json"}),
    path('csv/', include((api_patterns, "csv")), {"fmt":"csv"}),
]

WebPrototype/flightdata/views.py
"""
Django views for FlightData backend
Author: Jack Lardner, Ross Curley
Date last modified: 29/10/19

Views process a user's request and returns a response
"""

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.views import View
from django.views.generic import ListView, DetailView
from decimal import Decimal
import datetime
from .models import *


class AirportView(View):
    """View for the Airport model"""

    template = 'flightdata/airports.html'

    def get(self, request):
        airport_list = Airport.objects.all()
        context = {
            'airport_list': airport_list,
        }
        return render(request, self.template, context)


class AirlineView(View):
    """View for the Airline model"""

    template = 'flightdata/airlines.html'

    def get(self, request):
        airline_list = Airline.objects.all()
        context = {
            'airline_list': airline_list,
        }
        return render(request, self.template, context)


class AircraftView(View):
    """View for the Aircraft model"""

    template = 'flightdata/aircraft.html'

    def get(self, request):
        aircraft_list = Aircraft.objects.all()
        context = {
            'aircraft_list': aircraft_list,
        }
        return render(request, self.template, context)

def is_valid_query(param):
        return param != '' and param is not None

class FlightInfoView(View):
    """View for the FlightInfo model"""

    template = 'flightdata/flights.html'

    def filter(self, request):
        """Filter request from html form and return query results."""
        # start with every results
        query = FlightInfo.objects.all().order_by('-departure_time') 
        # get fields from get request
        flight = request.GET.get('search_flight')
        airline = request.GET.get('airline')
        origin = request.GET.get('origin_airport')
        destination = request.GET.get('destination_airport')
        depart = request.GET.get('departure_date')
        arrive = request.GET.get('arrival_date')
        results = request.GET.get('results')

        # for every valid query filter dater accordingly 
        try:
            if (is_valid_query(flight)):
                query = query.filter(flight_number__icontains=flight)

            if (is_valid_query(airline)):
                query = query.filter(airline__exact=airline)

            if (is_valid_query(origin)):
                query = query.filter(origin__iata_code__iexact=origin)

            if (is_valid_query(destination)):
                query = query.filter(destination__iata_code__iexact=destination)

            if (is_valid_query(depart)):
                query = query.filter(departure_time__gte=depart)
            
            if (is_valid_query(arrive)):
                query = query.filter(arrival_time__lte=arrive)

            if (is_valid_query(results)):
                query = query[:int(results)]
        except (ValidationError, Exception) as err:
            print(err)
        finally:
            return query

    def get(self, request):
        """ handle get request from user """
        # filter request from user
        flight_info_list = self.filter(request)
        airline_list = Airline.objects.all()
        airports = Airport.objects.all()
        context = {
            'flights': flight_info_list,
            'airlines': airline_list,
            'airports': airports
        }
        return render(request, self.template, context)

class FlightStatusView(View):
    """View for the FlightStatus model"""

    template = 'flightdata/flightstatus.html'

    def get(self, request, flight_number):
        """ filter get request from user."""
        flight_status_list = FlightStatus.objects.filter(
            flight_id__exact=flight_number)
        context = {
            'flights': flight_status_list,
            'flight_number': flight_number
        }
        return render(request, self.template, context)


class AirfareView(View):
    """View for the Airfare model"""

    template = 'flightdata/airfares.html'

    def filter(self, request):
        """Filter request from html form and return query results."""
        # start with every results
        query = Airfare.objects.all()
        # get fields from get request
        search_class = request.GET.get("search_class" )
        search_type = request.GET.get("search_type")
        min_fare = request.GET.get("min_fare")
        max_fare = request.GET.get("max_fare")
        flight = request.GET.get("search_flight")
        date = request.GET.get("search_date")
        results = request.GET.get("results")

        # for every valid query filter dater accordingly 
        try:
            if is_valid_query(search_class):
                query = query.filter(fare_class__icontains=search_class)
            
            if is_valid_query(search_type):
                query = query.filter(fare_type__icontains=search_type)
            
            if is_valid_query(min_fare) and is_valid_query(max_fare):
                query = query.filter(fare__range=(float(min_fare), float(max_fare)))
            elif is_valid_query(min_fare):
                query = query.filter(fare__gte=float(min_fare))
            elif is_valid_query(max_fare):
                query = query.filter(fare__lte=float(max_fare))

            if is_valid_query(flight):
                query = query.filter(flight__flight_number__icontains=flight)

            if is_valid_query(date):
                query = query.filter(time_collected__gte=date)

            if (is_valid_query(results)):
                query = query[:int(results)]
        except (ValidationError, Exception) as err:
            print(err)
        finally:
            return query
           

    def get(self, request):
        """ handle get request from user."""
        airfares = self.filter(request)
        context = {
            'airfares': airfares,
        }
        return render(request, self.template, context)

class AirfareFlightView(View):
    """" View for a single flights airfare. """

    template = 'flightdata/flight_airfare.html'

    def get(self, request, flight_number):
        """ handle get request from users."""
        airfare_list = Airfare.objects.filter(flight_id__exact=flight_number)
        context = {
            'airfare_list': airfare_list,
            'flight_number': flight_number
        }
        return render(request, self.template, context)


class TrackedRouteView(View):
    """View for the TrackedRoutes model"""

    template = 'flightdata/routes.html'

    def filter(self, request):
        """Filter request from html form and return query results."""
        # start with every results
        query = TrackedRoute.objects.all().order_by('-start_tracking')
        # get fields from get request
        origin = request.GET.get("origin")
        destination = request.GET.get("dest")
        start = request.GET.get("start")
        stop = request.GET.get("stop")
        results = request.GET.get("results")

        try:
            if is_valid_query(origin):
                query = query.filter(origin__iata_code__exact=origin)

            if is_valid_query(destination):
                query = query.filter(destination__iata_code__exact=destination)

            if is_valid_query(stop):
                query = query.filter(stop_tracking__lte=stop)
                
            if is_valid_query(start):
                query = query.filter(start_tracking__gte=start)
            
            if is_valid_query(results):
                query = query[:int(results)] 
        except (ValidationError, OverflowError, Exception) as err:
            print(err)
        finally:
            return query

    def get(self, request):
        """filter get requests from users"""
        routes = self.filter(request)
        airports = Airport.objects.all()
        context = {
            'routes': routes,
            'airports': airports
        }
        return render(request, self.template, context)

WebPrototype/flightdata/templates/flightdata/aircraft.html
<h2>Aircraft</h2>
<table>
    <tr>
        <th>Make</th>
        <th>Model</th>
        <th>Num. Seats</th>
    </tr>
    {% for aircraft in aircraft_list %}
        <tr>
            <td>{{ aircraft.make }}</td>
            <td>{{ aircraft.model }}</td>
            <td>{{ aircraft.num_seats }}</td>
        </tr>
    {% endfor %}
</table>

WebPrototype/flightdata/templates/flightdata/airfares.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'flightdata/style.css' %}">
        <title> Airfares</title>
    </head>
    <body> 
        <div class="sitenav">
            <a href="{% url 'index' %}">Home</a>
            <a href="{% url 'flightdata:flight_info' %}">Flights</a>
            <a class="active" href="{% url 'flightdata:airfares' %}">Airfares</a>
            <a href="{% url 'flightdata:airports' %}">Airports</a>
            <a href="{% url 'flightdata:airlines' %}">Airlines</a>
            <a href="{% url 'flightdata:routes' %}">Routes</a>
            <a href="{% url 'settings' %}">Settings</a>
            <a href="{% url 'errors:scraper_logs' %}">Scraper</a>
            <a href="{% url 'admin:index' %}">Admin</a>
        </div>    
        <div class="main">
            <h1>Airfares</h1>
            <form action="./airfares" method="get">
                <div class="filter-row">
                    <div class="filter-col">
                        <label for="search_class">Class</label>
                        <input type="search" name="search_class" id="search_class" placeholder="Class">
                    </div>
                    <div class="filter-col">
                        <label for="search_type">Type</label>
                        <input type="search" name="search_type" id="search_type" placeholder="Type">
                    </div>
                    <div class="filter-col">
                        <label for="min_fare">Min Price</label>
                        <input type="number" name="min_fare" id="min_fare" min="0" placeholder="Min Price">
                    </div>
                    <div class="filter-col">
                        <label for="max_fare">Max Price</label>
                        <input type="number" name="max_fare" id="max_fare" min="0" placeholder="Max Price">
                    </div>
                </div>
                <div class="filter-row">
                    <div class="filter-col">
                        <label for="search_flight">Flight</label>
                        <input type="search" id="search_flight" name="search_flight" placeholder="Search Flight..." />                        
                    </div>     
                    <div class="filter-col">
                        <label for="search_date">Date</label>
                        <input type="date" name="search_date" id="search_date">
                    </div>
                    <div class="filter-col">
                        <label for="results">Results</label>
                        <select name="results" id="results">
                            <option value="" disabled selected>All</option>
                            <option value="25">25</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                        </select>
                        <button type="submit">Search</button>
                    </div>
                </div>
            </form>
            <table>
                <tr>
                    <th>Flight Number</th>
                    <th>Time Collected</th>
                    <th>Fare Class</th>
                    <th>Fare Type</th>
                    <th>Fare</th>
                </tr>
                {% for airfare in airfares %}
                    <tr>
                        <td>{{ airfare.flight.flight_number }}</td>
                        <td>{{ airfare.time_collected }}</td>
                        <td>{{ airfare.fare_class }}</td>
                        <td>{{ airfare.fare_type }}</td>
                        <td>{{ airfare.fare }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </body>
</html>

WebPrototype/flightdata/templates/flightdata/airlines.html
<!DOCTYPE html>
<html>
    
    <head>
        <title>Routes</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'flightdata/style.css' %}">
    </head>   
    <body>
        <div class="sitenav">
            <a href="{% url 'index' %}">Home</a>
            <a href="{% url 'flightdata:flight_info' %}">Flights</a>
            <a href="{% url 'flightdata:airfares' %}">Airfares</a>
            <a href="{% url 'flightdata:airports' %}">Airports</a>
            <a class="active" href="{% url 'flightdata:airlines' %}">Airlines</a>
            <a href="{% url 'flightdata:routes' %}">Routes</a>
            <a href="{% url 'settings' %}">Settings</a>
            <a href="{% url 'errors:scraper_logs' %}">Scraper</a>
            <a href="{% url 'admin:index' %}">Admin</a>
        </div>
        <div class="main">
            <h1>Airlines</h1>
            <table>
                <tr>
                    <th>Name</th>
                    <th>Website</th>
                </tr>
                {% for airline in airline_list %}
                <tr>
                    <td>{{ airline.name }}</td>
                    <td>{{ airline.website }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </body>
</html>

WebPrototype/flightdata/templates/flightdata/airports.html
<!DOCTYPE html>
<html>
    
    <head>
        <title>Airports</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'flightdata/style.css' %}">
    </head>   
    <body>
        <div class="sitenav">
            <a href="{% url 'index' %}">Home</a>
            <a href="{% url 'flightdata:flight_info' %}">Flights</a>
            <a href="{% url 'flightdata:airfares' %}">Airfares</a>
            <a class="active" href="{% url 'flightdata:airports' %}">Airports</a>
            <a href="{% url 'flightdata:airlines' %}">Airlines</a>
            <a href="{% url 'flightdata:routes' %}">Routes</a>
            <a href="{% url 'settings' %}">Settings</a>
            <a href="{% url 'errors:scraper_logs' %}">Scraper</a>
            <a href="{% url 'admin:index' %}">Admin</a>
        </div>
        <div class="main">
            <h1>Airports</h1>
            {% for airport in airport_list %}
            <button class="accordion"><b>{{ airport.name }}</b></button>
            <div class="panel">
                <table>
                    <th>IATA Code</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                    <th>Timezone</th>
                    <tr>
                        <td>{{ airport.iata_code }}</td>
                        <td>{{ airport.latitude }}</td>
                        <td>{{ airport.longitude }}</td>
                        <td>{{ airport.timezone }}</td>
                    </tr>
                </table>
            </div>
            {% endfor %}
            <script src="{% static 'flightdata/site_script.js' %}"></script>
        </div>
    </body>
</html>

WebPrototype/flightdata/templates/flightdata/flight_airfare.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'flightdata/style.css' %}">
        <title> Airfares</title>
    </head>
    <div class="sitenav">
            <a href="{% url 'index' %}">Home</a>
            <a href="{% url 'flightdata:flight_info' %}">Flights</a>
            <a href="{% url 'flightdata:airfares' %}">Airfares</a>
            <a href="{% url 'flightdata:airports' %}">Airports</a>
            <a href="{% url 'flightdata:airlines' %}">Airlines</a>
            <a href="{% url 'flightdata:routes' %}">Routes</a>
            <a href="{% url 'settings' %}">Settings</a>
            <a href="{% url 'errors:scraper_logs' %}">Scraper</a>
            <a href="{% url 'admin:index' %}">Admin</a>
        </div>
    <div class="main">
        <h1>{{ flight_number }}</h1>
        <table>
            <tr>
                <th>Time Collected</th>
                <th>Fare Class</th>
                <th>Fare Type</th>
                <th>Fare</th>
            </tr>    
            {% for airfare in airfare_list %}
            <tr>
            <td>{{ airfare.time_collected }}</td>
            <td>{{ airfare.fare_class }}</td>
            <td>{{ airfare.fare_type }}</td>
            <td>{{ airfare.fare }}</td>
            </tr>
            {% endfor %}
        </table>
        <a href="{% url 'flightdata:flight_info' %}">Back</a>
    </div>
</html>

WebPrototype/flightdata/templates/flightdata/flights.html
<!DOCTYPE html>
<html>
    <head>
        <title>Flights</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'flightdata/style.css' %}">
    </head>
    <body>
    <div class="sitenav">
        <a href="{% url 'index' %}">Home</a>
        <a class="active" href="{% url 'flightdata:flight_info' %}">Flights</a>
        <a href="{% url 'flightdata:airfares' %}">Airfares</a>
        <a href="{% url 'flightdata:airports' %}">Airports</a>
        <a href="{% url 'flightdata:airlines' %}">Airlines</a>
        <a href="{% url 'flightdata:routes' %}">Routes</a>
        <a href="{% url 'settings' %}">Settings</a>
        <a href="{% url 'errors:scraper_logs' %}">Scraper</a>
        <a href="{% url 'admin:index' %}">Admin</a>s
    </div>
    <div class="main">
    <h1>Flights</h1>
    <form method="GET" action="./flights">
        <div class="filter-row">
            <div class="filter-col">
                <label for="search_filght">Flight</label>
                <input type="search" id="search_flight" name="search_flight" placeholder="Search Flight..." />                
            </div>
            <div class="filter-col">
                <label for="airlne">Airline</label>
                <select id="airline" name="airline">
                    <option value="" disabled selected>Choose Airline</option>
                    {% for airline in airlines %}
                    <option value="{{ airline.name }}">{{ airline.name }}</option>
                    {% endfor %}
                </select>
            </div>      
        </div>
        <div class="filter-row">
            <div class="filter-col">
                <label for="origin_airport">Origin Airport</label>
                <select name="origin_airport" id="origin_airport">
                    <option value="" disabled selected>Choose Airport</option>
                    {% for airport in airports %}
                    <option value="{{ airport.iata_code }}">{{ airport.name }}</option>
                    {% endfor %}
                </select>       
            </div>
            <div class="filter-col">
                <label for="destination_airport">Destination Airport</label>
                <select name="destination_airport" id="destination_airport">
                    <option value="" disabled selected>Choose Airport</option>
                    {% for airport in airports %}
                    <option value="{{ airport.iata_code }}">{{ airport.name }}</option>
                    {% endfor %}
                </select>  
            </div>
        </div>
        <div class="filter-row">
            <div class="filter-col">
                <label for="departure_date">Departure</label>
                <input type="date" id="departure_date" name="departure_date" placeholder="Departure Date">
            </div>
            <div class="filter-col">
                <label for="arrival_date">Arrival</label>
                <input type="date" id="arrival_date" name="arrival_date" placeholder="Arrival Date">
            </div>
            <div class="filter-col">
                <label for="results">Results</label>
                <select name="results" id="results">
                    <option value="" disabled selected>All</option>
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
                <button type="submit">Search</button>
            </div>
        </div>
    </form>
    {% for flight in flights %}    
    <button class="accordion"><b>{{ flight.flight_number }}</b>&emsp;<b>{{ flight.origin.iata_code }}</b> <b>&RightArrow;</b> <b>{{ flight.destination.iata_code }}</b>&emsp;<b>{{ flight.airline.name }}</b>&emsp;<b>{{ flight.departure_time }}</b></button>
    <div class="panel">
        <table>
            <tr>
                <th>Flight Number</th>
                <th>Departure Time</th>
                <th>Arrival Time</th>
                <th>Origin</th>
                <th>Destination</th>
                <th>Airline</th>
                <th>Aircraft Model</th>
            </tr>        
            <td>{{ flight.flight_number }}</td>
            <td>{{ flight.departure_time }}</td>
            <td>{{ flight.arrival_time }}</td>
            <td><a href="{% url 'flightdata:airports' %}">{{ flight.origin.iata_code }}</a></td>
            <td><a href="{% url 'flightdata:airports' %}">{{ flight.destination.iata_code }}</a></td>
            <td><a href="{% url 'flightdata:airlines' %}">{{ flight.airline.name }}</a></td>
            <td>{{ flight.aircraft_model.make }} {{ flight.aircraft_model.model }}</td>
        </table>
        
        <a href="{% url 'flightdata:flight_status' flight.flight_number %}">Status History</a> 
        <a href="{% url 'flightdata:airfare' flight.flight_number %}">Airfare History</a>
    </div>
    {% endfor %}
    <script src="{% static 'flightdata/site_script.js' %}"></script>
    </div>
</body>
</html>

WebPrototype/flightdata/templates/flightdata/flightstatus.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'flightdata/style.css' %}">
        <title>{{ flight_number }}</title>
    </head>
    <div class="sitenav">
            <a href="{% url 'index' %}">Home</a>
            <a href="{% url 'flightdata:flight_info' %}">Flights</a>
            <a href="{% url 'flightdata:airfares' %}">Airfares</a>
            <a href="{% url 'flightdata:airports' %}">Airports</a>
            <a href="{% url 'flightdata:airlines' %}">Airlines</a>
            <a href="{% url 'flightdata:routes' %}">Routes</a>
            <a href="{% url 'settings' %}">Settings</a>
            <a href="{% url 'errors:scraper_logs' %}">Scraper</a>
            <a href="{% url 'admin:index' %}">Admin</a>
        </div>
    <div class="main">
        <h1>{{ flight_number }}</h1>
            <table>
                <tr>
                    <th>Time Collected</th>
                    <th>Departure Time</th>
                    <th>Departure Status</th>
                    <th>Arrival Time</th>
                    <th>Arrival Status</th>
                </tr>    
                {% for flight in flights %}
                <tr>
                    <td>{{ flight.time_collected }} </td>
                    <td>{{ flight.departure_time }}</td>
                    <td>{{ flight.departure_status }}</td>
                    <td>{{ flight.arrival_time }}</td>
                    <td>{{ flight.arrival_status }}</td>
                </tr>
                {% endfor %}
            </table>
            <a href="{% url 'flightdata:flight_info' %}">Back</a>
    </div>
</html>

WebPrototype/flightdata/templates/flightdata/routes.html
<!DOCTYPE html>
<html>
    
    <head>
        <title>Routes</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'flightdata/style.css' %}">
    </head>   
    <body>
        <div class="sitenav">
            <a href="{% url 'index' %}">Home</a>
            <a href="{% url 'flightdata:flight_info' %}">Flights</a>
            <a href="{% url 'flightdata:airfares' %}">Airfares</a>
            <a href="{% url 'flightdata:airports' %}">Airports</a>
            <a href="{% url 'flightdata:airlines' %}">Airlines</a>
            <a class="active" href="{% url 'flightdata:routes' %}">Routes</a>
            <a href="{% url 'settings' %}">Settings</a>
            <a href="{% url 'errors:scraper_logs' %}">Scraper</a>
            <a href="{% url 'admin:index' %}">Admin</a>
        </div>
        <div class="main">
            <h1>Routes</h1>
            <form action="./routes" method="get">
                <div class="filter-row">
                    <div class="filter-col">           
                        <label for="origin">Origin</label>
                        <select name="origin" id="origin">
                            <option value="" disabled selected>Choose Airport</option>
                            {% for airport in airports %}
                            <option value="{{ airport.iata_code }}">{{ airport.iata_code }}</option>
                            {% endfor %} 
                        </select>
                    </div>
                    <div class="filter-col">
                        <label for="dest">Destination</label>
                        <select name="dest" id="dest">
                            <option value="" disabled selected>Choose Airport</option>
                            {% for airport in airports %}
                            <option value="{{ airport.iata_code }}">{{ airport.iata_code }}</option>
                        {% endfor %}
                    </select>    
                    </div>
                    <div class="filter-col">
                        <label for="start">Started Tracking</label>
                        <input type="date" name="start" id="start">
                    </div>
                    <div class="filter-col">
                        <label for="stop">Stopped Tracking</label>
                        <input type="date" name="stop" id="stop">
                    </div>
                    
                </div>
                <div class="filter-row">
                    <div class="filter-col">
                        <label for="results">Results</label>
                        <select name="results" id="results">
                            <option value="" disabled selected>All</option>
                            <option value="25">25</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                        </select>
                        <button type="submit">Search</button>
                    </div>
                </div>
            </form>
            <table>
            <tr>
                <th>Origin</th>
                <th>Destination</th>
                <th>Started Tracking</th>
                <th>Stopped Tracking</th>
            </tr>
            {% for route in routes %}
            <tr>
                <td>{{ route.origin.name }}</td>
                <td>{{ route.destination.name }}</td>
                <td>{{ route.start_tracking }}</td>
                <td>{{ route.stop_tracking }}</td>
            </tr>
            {% endfor %}
            </table>
        </div>
    </body>
</html>